server:
  port: 63004

spring:
  application:
    name: bicyclestore-order-service
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, shutdown
  endpoint:
    shutdown:
      enabled: true

logging:
    config: classpath:logback.xml
